# Generated by Django 4.1.2 on 2022-10-27 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_bookinstance_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('can_display_all_borrowed', 'Display all borrowed books'), ('can_renew', 'Set dueback date'))},
        ),
    ]
