# Generated by Django 4.1.2 on 2022-10-28 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_bookinstance_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['last_name', 'first_name'], 'permissions': (('can_change_authors', 'Can create, update or delete an author'),)},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': (('can_change_books', 'Can create, update or delete a book'),)},
        ),
    ]
